### ISSUE TITLE
The SQL Server instance returned an invalid or unsupported protocol version during login negotiation.

### ISSUE THREAD

**Issue by kgbuddhima** [StackExchange/Dapper#687] opened 2017-01-27 06:13 UTC
I'm using Dapper dot net **1.50.2** in my.Net core project. with SQL server 2016 as the database. when I run CRUD operation in my development environment with SQL Server 2016 it works fine.

But when I release it to the live environment, It gave me the below exception..,

> The SQL Server instance returned an invalid or unsupported protocol version during login negotiation.

The Live environment has SQL server 2000 database. 

I'm using dapper .net **1.4.0** in my other windows and web applications. They works fine with SQL server 200 database.

 **Is it a compatible issue in SQL Server 2000 with dapper v 1.50.2**

**Comment by rhubley** [comment] 2017-01-27 11:18
Dapper isn't the issue here. Check to see if your connection object supports SQL 2000 and that you are using the correct connection string.

**Comment by NickCraver** [comment] 2017-01-28 14:14
This appears to be like a TLS issue between client and server. The problem is not Dapper as @rhubley, but potentially referenced ADO.NET libraries underneath, which Dapper builds on top of.

**Comment by NickCraver** [comment] 2018-05-21 00:59
Closing this out as it's not a Dapper, but a library (underneath) or configuration issue. For anyone else finding this: yep, Dapper supports SQL Server 2000 (it doesn't really care).

**Closed by NickCraver** 2018-05-21 00:59 UTC
