### ISSUE TITLE
Query Cancellation doesn't work as expected while streaming query results

### ISSUE THREAD

**Issue by j2jensen** [StackExchange/Dapper#1088] opened 2018-08-01 20:29 UTC
When using a cancellation token on a Query command that begins returning results almost immediately, but takes a long time to return all those results (e.g. `select id from table1` where table1 has a hundred million rows), it appears that the cancellation token causes Dapper to try cancelling the connection, but for whatever reason the connection-cancelling attempt itself takes a long time. 

```
using (SqlConnection connection = new SqlConnection("/* Some connection string */"))
{
	var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
	connection.Open();
	var cd = new CommandDefinition("select id from table1",
		commandTimeout: 3, 
		cancellationToken: cts.Token);
	await connection.QueryAsync<string>(cd);
}
```
What will NOT happen with the code above:
- SqlException after 3 seconds; Because commandTimeout applies to each Read() in network traffic, as long as the connection keeps streaming values it will never time out.
- TaskCanceledException after 5 seconds; This is what I would expect to happen. I'm not clear why it doesn't.

What WILL happen with the code above:
- SqlException after 8 seconds; My best guess is that the attempt to cancel the query is getting blocked somehow until the network Read() times out after three more seconds.

**Comment by NickCraver** [comment] 2020-05-04 02:51
Unfortunately, this is at the mercy of the provider (we're just passing it along). What you are observing is indeed what we have seen in SQL Server as well. I would normally suggest filing an issue there but...I really don't think this behavior is going to ever be changed (and there'd be a performance penalty in doing so).

Going to close this out since it is expected behavior, but your writeup is much appreciated for anyone else finding this. We went through a healthy sanity check phase when direct discovering this as well.

**Closed by NickCraver** 2020-05-04 02:51 UTC
