### ISSUE TITLE
Why are all of the dotnetfiddles broken?

### ISSUE THREAD

**Issue by colemars** [StackExchange/Dapper#1329] opened 2019-09-18 23:05 UTC
https://dotnetfiddle.net/qTvEME
https://dotnetfiddle.net/vIvUNm
https://dotnetfiddle.net/1K2DU4

**Comment by mgravell** [comment] 2019-09-19 17:52
Because they are targeting .net 4.5, and the current version of dapper
doesn't work on 4.5 any more.

**Comment by NickCraver** [comment] 2019-09-21 13:03
@mgravell hmmm, I think this is another manifestation of `netstandard2.0` oddities - recommend we push the TFM addition that's in `master` out to NuGet after a dogfood. Given that Monday is .NET Conf and 3.0 is being released then, I want to build a new package. This is also due to https://github.com/dotnet/core/issues/3388 - I think we need to re-create the packages with `<Deterministic>false</Deterministic>` before releasing to the NuGet gallery.

**Comment by JonathanMagnan** [comment] 2019-10-14 23:08
All Fiddle has been updated on our side to use the v1.60.6, so they should now work again with the v1.x

While it fixes all existing Fiddle, it will not fix future Fiddle that will be created in the v2.x

Since the issue is in .NET Fiddle and not in Dapper, feel free to close it whenever you want.

Best Regards,

Jonathan

**Closed** 2019-10-14 23:10 UTC
