### ISSUE TITLE
Adding new keys to DapperRow is not thread safe

### ISSUE THREAD

**Issue by evgenyAtInsightly** [StackExchange/Dapper#1024] opened 2018-05-15 16:12 UTC
We came across a few issues when using Dapper in our ASP.NET application, all related to race conditions when adding keys dynamically to DapperRow from multiple threads. The one I was able to reproduce fairly easily is IndexOutOfRangeException when trying to add a new key to DapperRow. We get DapperRow when we call Query<dynamic> method. Below is the program I used to reproduce the issue.

I realize this might be by design and we are probably shooting ourselves in the foot by casting to IDictionary<string,object>. However, I couldn't find any documentation on the limitation. Can you please confirm if there is no plan to fix this?

**Code**

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            new Program().Run();
        }

        private void Run()
        {
            var allThreads = new List<Thread>();
            for (var i = 0; i < 4; i++)
            {
                var counter = i;
                var thread = new Thread(() => QueryThread(counter));
                thread.Start();
                allThreads.Add(thread);
            }

            allThreads.ForEach(x => x.Join());
        }

        void QueryThread(int counter)
        {
            var connection = new SqlConnection("...");
            for (var i = 0; i < 200; i++)
            {
                try
                {
                    var items = connection.Query<dynamic>("select top(20) * from AnyTable", null).ToList();
                    var rowindex = 0;
                    foreach (var item in items)
                    {
                        var row = (IDictionary<string, object>)item;
                        row.Add($"value_{counter}_{i}_{rowindex++}", i);
                    }
                }
                catch (Exception error)
                {
                    // Getting a lot of Index was outside the bounds of the array
                    Console.WriteLine(error.Message);
                }
            }
        }
    }
}
```

**Exception**
```
System.IndexOutOfRangeException
   at Dapper.SqlMapper.DapperRow.SetValue(String key, Object value, Boolean isAdd)
```

**Comment by NickCraver** [comment] 2018-05-20 12:56
Closing out to cleanup here - indeed behaving as intended. Not all collections are thread safe, since that adds overhead for everyone.

**Closed by NickCraver** 2018-05-20 12:56 UTC
