### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in System.Data.OleDb.dll

### ISSUE THREAD

**Issue by MarcinSiennicki** [StackExchange/Dapper#1494] opened 2020-07-03 08:32 UTC
Hello, 
Using the .net Core application with the .net Standard library in which the dapper is used, an error occurred (below) . The OleDbConnection is used to create a connection.  The problem is with a insert parametrization query. Update nad Delete work fine. The same library code work fine with .net Framework.

_connection.Query($"INSERT INTO [{tableName}] ({properties}) VALUES ({propertiesValues})", value);_

**System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
An unhandled exception of type 'System.AccessViolationException' occurred in System.Data.OleDb.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.**

**Comment by bgrainger** [comment] 2020-07-14 16:49
This sounds like a problem with System.Data.OleDb, not with Dapper. Possibly a duplicate of https://github.com/dotnet/runtime/issues/36954 or you might need to open a new issue on the dotnet/runtime repository.

**Comment by MaceWindu** [comment] 2020-08-05 15:29
@MarcinSiennicki if you have easy repro code, please add it to referenced issue, as I cannot reproduce it easily

**Comment by NickCraver** [comment] 2020-08-15 13:41
Indeed this isn't a Dapper issue - is deeper and agree with @bgrainger here. I hope you're able to track down the lower level issue!

**Closed by NickCraver** 2020-08-15 13:41 UTC
