### ISSUE TITLE
Specific test shows EF faster than Dapper

### ISSUE THREAD

**Issue by jfware** [StackExchange/Dapper#691] opened 2017-02-03 19:59 UTC
I've been working on a change to our DAL to use Dapper and show performance benefits. In one specific case however Dapper is significantly slower. All testing was done in Release mode and start without debugging from Visual Studio.

I'm running the test to hit my web api with 50k calls via Parallel.ForEach in LINQPad. If my code determines that the record already exists then it will not insert a new one. This means that I first look for a record and when it doesn't exist I insert one. In this particular test it means that there will be 100k queries against the database because none in fact exist. I want to see how long it takes EF vs Dapper to insert all 50k records.

EF6 is pretty fast. 00:22.421 with average of 6.923(ms)
Dapper is pretty slow: 02:04.539 with average of 40.803(ms)
ADO.NET is fastest: 00:10.684 with average of 3.009(ms)

Using the Visual Studio Performance Wizard I tracked this down to the connection.Query<T> part that checks if the record exists before the insert first being the slowest part. 

Here is the C# code (Query):
```c#
var sql = "select top 1 SomeId,SomeOtherId,Description,IsActive,LastModifiedDate from SomeTable where someId = @someId and someOtherId = @someOtherId";
var entity = conn.Query<SomeTable>(sql, new { someId, someOtherId }).FirstOrDefault();
```
With that I turned up a stackoverflow [question](http://stackoverflow.yoobaidu.com/questions/38533752/bad-dapper-performance-for-parametrized-queries) where someone mentioned a similar problem but had no answers.

I changed my connection.Query<T> to use string.Format instead of passing an anonymous type, as was done in the SO question, and that fixed the problem for me too. Obviously not something I will put into production.

Fast code:
```c#
var sql = "select top 1 someId,someOtherId,Description,IsActive,LastModifiedDate from SomeTable where someId = '{0}' and someOtherId = '{1}'";
var entity = conn.Query<SomeTable>(string.Format(sql, someId, someOtherId)).FirstOrDefault();
```
Dapper (string.Format): 00:17.781 with average of 5.466(ms)

I wondered if it might be because the Query part never returns anything so some internal optimization was getting skipped so I decided to force the very first insert to do a query that would be a hit and then never do that part again after that. The results are better but still much slower than EF6.

Dapper (forced Query): 00:47.389 with average of 17.377(ms)

My table is very simple:
```sql
CREATE TABLE [dbo].[SomeTable](
	[SomeId] [varchar](15) NOT NULL,
	[SomeOtherId] [varchar](50) NOT NULL,
	[Description] [varchar](255) NULL,
	[IsActive] [bit] NOT NULL,
	[LastModifiedDate] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_SomeTable] PRIMARY KEY CLUSTERED 
(
	[SomeId] ASC,
	[SomeOtherId] ASC
)
```
Any ideas what I can try? I feel like it must be something with my narrow test case but I was very surprised at how much faster EF6 is than Dapper for this test.

**Comment by NickCraver** [comment] 2017-02-12 20:16
Do you have a LINQPad script or minimal app that reproduces this? I'd be happy to take a look. If you have that repro handy, it'd save some time.

**Comment by jfware** [comment] 2017-02-13 20:54
I'm not having any luck reproducing the issue outside of the way it was behaving inside our application. I will keep digging and if I gather any new information I'll come back.

**Comment by NickCraver** [comment] 2017-02-13 23:51
Please keep me updated if you're able to repro, I'm very curious - we take pride in performance over here ;)

**Comment by NickCraver** [comment] 2017-08-20 21:27
Any news here? I've updated all the benchmarks in our repo if that helps.

**Comment by jfware** [comment] 2017-08-21 13:00
Unfortunately I haven't been able to reproduce the problem. I think at this point we can chalk it up to something I was doing wrong. Thanks for the willingness to help!

**Comment by philhaynes** [comment] 2018-06-21 14:07
I know this is an old discussion but the slow code in the example given was almost certainly caused by passing a string parameter (NVARCHAR) to a query that's comparing the parameter value with the VARCHAR field "SomeOtherId". SQL Server really doesn't like this (especially if the table being queried is big).

In the fast code example (where the actual string is used in the query as a quoted value) it runs fast since the SomeOtherId='blah' comparison is comparing VARCHAR SomeOtherId with 'blah' (also a VARCHAR). As such, no casting is needed and the query runs much faster. I think I'm right in saying that SQL Server casts the table data in this situation, rather than the constant that the data is being compared with (hence the query slows more and more as the table grows).

**Comment by NickCraver** [comment] 2018-09-11 02:33
Closing out for the reasons above - I agree this is a very likely cause :)

**Closed by NickCraver** 2018-09-11 02:33 UTC
Labels: needs-info
