### ISSUE TITLE
unexpected errors sometimes with opening connection

### ISSUE THREAD

**Issue by kirakosyan** [StackExchange/Dapper#656] opened 2016-12-07 14:21 UTC
Hi 
I have strange error with opening connection. I would like to say the project has 100s of other calls using dapper (huge project) and it works perfect. There is only one call to insert a record fails sometime, like once per 1000 requests. 
So the method is very simple. I removed some columns to keep it short.
I tried to Execute async and not asnc. I tried to open connection myself and close myself.
I know that dapper is opening connection itself if it is closed so this works ideally in 99% 

Exception  "Invalid operation. The connection is closed."
sometimes it says " The connection was not closed. The connection's current state is connecting."

Why it sometimes fails to open connection?

```c#
public async Task<int> AddMessage(Message message)
{            
    using (_connection = new SqlConnection(_connectionstring))
    {
        const string query = @"
            INSERT INTO SMS (Message) 
            VALUES (@Message);
            select scope_identity();";
        try
        {
            var result = await _connection.ExecuteScalarAsync<int>(query, message);
            return result;
        }
        catch (Exception e)
        {
            Logger.Error(e, "Unable to create SMS from " + JsonConvert.SerializeObject(message));
            throw;
        }
    }
}
```

**Comment by NickCraver** [comment] 2017-01-28 16:08
It's possible that `ExecuteScalarAsync` does not wait for an open (or any of our Async methods do). Needs investigation, tagging.

**Comment by mgravell** [comment] 2017-01-29 10:31
question: are you passing in a cancellation token? I wonder if the problem
relates to activated cancellations - we might not be actively checking the
cancellation state (deferring that to the provider)

**Comment by jcoutch** [comment] 2017-06-27 18:34
@mgravell and @NickCraver - From what I can tell, when multiple calls are performed against the same database connection in parallel, the checks for the database's state (the `wasClosed` variable) aren't taking multiple threads into account.  Both calls will have `wasClosed` set to true, which causes a race condition between both queries.  The first query that finishes closes the connection, causing the second query/close command to throw an exception.

This is similar to issue #758.  I created a project that (crudely) reproduces the issue using fake database connections/commands/readers:
https://github.com/jcoutch/dapper-issue-758-repro

I have some ideas on how to fix this:
- Make `wasClosed` a locked nullable variable.  The first query to check the connection state is the query that sets the variable to `true`/`false` (if `wasClosed` is `null`.)
- Each call to Execute/Query (both sync/async) increments a thread-safe counter on start, and decrements when it's complete.
- The query that decrements the counter to zero is the one that checks the `wasClosed` variable, closes the connection if needed, and sets it back to `null`.

Thoughts?

**Comment by mgravell** [comment] 2017-06-27 18:55
ado.net itself does not claim thread safety on a single connection (see the
thread safety notes on DbConnection), so anything above that is moot. The
only supported scenario here would be async+MARS, but even that would only
be guaranteed when a single thread is actively working against the
connection.

Thread safety is a very particular beast. Can you please be **very
specific** about what your threading scenario is? If you're casually
accessing a single connection from multiple threads: I'm pretty sure that's
a completely unsupported and unsupportable use case - the underlying
providers don't support that.

**Comment by mgravell** [comment] 2017-06-27 19:51
I've checked the code in the linked repro (thanks for that), and indeed:
this is just incorrect usage. There's no benefit us worry about making the
open/close work "correctly" (if such a thing can be defined in this case),
because *everything else* in the repro is also - as far as I cab tell -
fundamentally broken.

You are not meant to talk to a connection arbitrarily from multiple
threads. You either need to isolate or synchronize.

**Comment by jcoutch** [comment] 2017-06-27 20:19
The sample project above was just to consistently reproduce the effect we're seeing.  That's not how our actual code is structured (we're not actively trying to run commands against the same connection in multiple threads.)

In our case, we're using Ninject for creating the connection within a named scope, and the context is per request.  All calls *should* be running asynchronously.  We're currently using async + MARS.  Our connection provider (implementing Ninject.Activation.Provider) handles opening the connection before any queries are ran against it.  Once in a while, we'll get a connection closed at random, which throws an exception.  To debug what was calling the .Close() method, we wrapped our connection object with our own implementation of IDbConnection, and anytime .Close() is called, wrote a stack trace to the log.  The culprit turned out to be Dapper calling .Close(), and from what I could tell in the source code, .Close() is associated with the areas of the code I identified above.  That's what led me down that wild goose chase.  :-)

I'm going to do a bit more detective work...see if everything is being scoped correctly within our DI container, if someone threw in a stray Task.Run I'm not aware of, etc.  But, at the very least, the sample code above will give others something to look into if they're running into a similar issue.  If I find anything, I'll let you know.

**Comment by mgravell** [comment] 2017-06-27 21:37
My curiosity is piqued, but as you can see in the dapper code : it only
closes what it opens. So then the question becomes: why was it not open (or
why did dapper think that it was not open, which it does by reading the
connection status). When you open the connections, I wonder if you are
doing an OpenAsync and not awaiting? but that's just a random idea
obviously. Perhaps also tracking what code is *opening* the connection
would be good, to look for irregularities?

**Comment by jcoutch** [comment] 2017-07-07 17:21
After some more research, our issue turned out to be SqlClient that was closing the connection.  Apparently, when you're using connection pools, and there's a timeout, SqlClient closes the connection (see line 2049):

https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/TdsParserStateObject.cs,90eff897592ec29d,references

Not sure if this is the same issue @kirakosyan is seeing, but thought I'd toss it out there.

**Comment by NickCraver** [comment] 2018-05-20 13:31
Closing this one out as the root is: "don't do that". Running multiple concurrent queries on a single connection (sans MARS) is something unsupported by the entire platform. It's not specifically a Dapper issue nor something we could fix.

On the timeout issue, @jcoutch thanks for he digging and update here. I'm sure someone later will find this and be quite grateful you did :)

**Closed by NickCraver** 2018-05-20 13:31 UTC
Labels: needs-investigation
