### ISSUE TITLE
Database link on Oracle problem

### ISSUE THREAD

**Issue by langecz** [StackExchange/Dapper#496] opened 2016-04-05 09:29 UTC
Hi, i have problem with database links on Oracle.

I use unmanaged oracle driver and this piece of code:

``` c#
using (var connection = DatabaseProvider.Connection)
{
    const string baseSql = @"SELECT ColumnName FROM TableName@DatabaseLinkName WHERE id = 1";
    connection.Open();
    var cmd = connection.CreateCommand();
    cmd.AddToStatementCache = false;
    cmd.CommandText = commandText;
    var result = cmd.ExecuteScalar();
    connection.Close();
}
```

When i run this code 5 times, everything works right.

When i use dapper:

``` c#
using (var connection = DatabaseProvider.Connection)
{
    const string baseSql = @"SELECT ColumnName FROM TableName@DatabaseLinkName WHERE id = 1";
    var result = connection.Query<string>(commandText).SingleOrDefault();
    connection.Close();
}
```

and run it 5 times, i get the error:

> ORA-02020: too many database links in use

It seems there stayes open cursor (or maybe some other problem?) and used database link is not closed.
Is there some way how to handle it, please?

Thanks a lot.

**Comment by mgravell** [comment] 2016-04-05 14:49
Question: if you use dapper's scalar method: does it work fine then? I'm
intrigued what the problem is, but to do a like for like comparison I'd
want to see both using scalar or both using reader.

If scalar works, I'd also be interested to see what happens if you use
`ExecuteReader` in the first example (the ado.net one) - basically, if we
can make it fail in the same way, we can hopefully fix it properly. But
first we need a like-for-like repro.

**Comment by langecz** [comment] 2016-04-05 22:21
Thanks for response.
OK, another example.

```
public class X
{
  public string column1 {get; set;}
  public string column2 {get; set;}
}
```

`const string commandText = @"SELECT column1, column2 FROM TableName@DatabaseLinkName WHERE id = 1";`

CASE 1 (works OK even if i call 5x)
```
using (var connection = DatabaseProvider.Connection)
{
  connection.Open();
  var cmd = connection.CreateCommand();
  cmd.AddToStatementCache = false;
  cmd.CommandText = commandText;
  var reader = cmd.ExecuteReader();
  if (!reader.HasRows) return null;
  reader.Read(); // take first row
  return = new X
  {
    column1 = reader[0].ToString(),
    column2 = reader[1].ToString(),
  }
}
```

While CASE 2 throws the ORA-02020 exception when i call the method fifth time
```
using (var connection = DatabaseProvider.Connection)
{
   var result = connection.Query<X>(commandText).SingleOrDefault();
   return result;
}
```

Is it what did you asked for?

**Comment by NickCraver** [comment] 2016-04-06 01:38
Oh Oracle, you're so awesome.
Just adding info here from hitting this before: this happens when you have more than 4 DB links open (hence the error on 5th run) in the same session.  I'm not sure exactly what ADO.NET is doing to close those DB links though. I'd first think the transaction behavior is what their provider hooks on here and we're doing it differently in Dapper.

**Comment by langecz** [comment] 2016-04-06 05:59
Exactly. Max count of opened links could be set by OPEN_LINKS on DB side, but it doesn't solve problem with Dapper. And I also suppose it has something to do with transactions. On DB side its enough when transaction is rollbacked and opened link is (should be?) deleted. And I also suppose it has something to do with ` cmd.AddToStatementCache = false;`, because without this command the behavior is the same for ADO.NET and Dapper (exception on 5th run).

**Comment by NickCraver** [comment] 2020-05-04 01:19
Going to close this out since it's an ADO.NET issue, given the info for `AddToStatementCache`, I'd recommend filing an issue on the provider itself!

**Closed by NickCraver** 2020-05-04 01:19 UTC
