### ISSUE TITLE
Error on web garbage - When passing parameters by position, each parameter can only be referenced once

### ISSUE THREAD

**Issue by briankitt** [StackExchange/Dapper#1442] opened 2020-04-28 02:08 UTC
On a web app, some garbage was entered into an input field.  Dapper blows up with a very strange error.   'When passing parameters by position, each parameter can only be referenced once'

Why is this happening?  What about this garbage is causing this strange error?

Microsoft SQL Server C#

Here is some SAMPLE code where you can reproduce this bug on your own system.
```cs
                using (var dbConn = new 
                SqlConnection(ConfigurationManager.ConnectionStrings["SqlServer"].ConnectionString))
                {
                    var mySqlText = @"
                    SELECT '??e??e?' AS T
                    INTO #Test
                    ";
                    dbConn.Execute(mySqlText, new { a = 1, b = 2 });
                }
```

**Comment by NickCraver** [comment] 2020-05-02 15:15
I'm honestly not sure what's _expected_ to happen here, can you please clarify? As it stands, I have no clue what you're trying to do...

**Comment by briankitt** [comment] 2020-05-02 17:06
This is not the actual SQL that blew up.   The actual SQL was an insert
statement, where I was inserting a 'contact me' form.

I put this *SAMPLE* together so you can test for yourself without the need
to have my database schema.

It's just a sample so you can easily recreate this for yourself.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by NickCraver** [comment] 2020-05-02 17:59
I understand it's a sample, I'm trying to convey: the sample SQL looks like gibberish - what is the _expected_ result of the sample? Just looking at it, I wouldn't have any expectations of what would or wouldn't work, because it doesn't make sense.

What is it you expect that sample to do?

**Comment by briankitt** [comment] 2020-05-02 18:21
Ok then.  Here's the problem.  Execute this, and tell me why it doesn't work.

using (var dbConn = new 
                SqlConnection(ConfigurationManager.ConnectionStrings["SqlServer"].ConnectionString))
                {
                    var mySqlText = @"
                    INSERT INTO tblContactForm
                    (FirstName, LastName, Subject, Email, Phone, Comments)
                    VALUES(@FirstName, @LastName, @Subject, @Email, @Phone, @Comments)
                    ";
                    dbConn.Execute(mySqlText, modelFormData);
                }

**Comment by NickCraver** [comment] 2020-05-02 18:27
What is `modelFormData` here? And what error if any are you getting? "It doesn't work" is very non-specific, please always include the error message of what it actually does...that's why we throw error messages :)

**Comment by briankitt** [comment] 2020-05-02 18:37
The error message is not only in the subject, but in my original comment.  

'When passing parameters by position, each parameter can only be referenced once'

I never once said 'it doesn't work', I was VERY specific.   I don't know where you read that, but I didn't say it.  I don't know how much simpler I could have made this for you, you are making this so complicated.

You shouldn't care what 'modelformdata' is, that's why I made the original code sample as simple as possible.   Why would you prefer my entire application over a couple of lines of code that will easily recreate the error on any person's environment with absolutely no other setup needed?

Simply grab that code from my original post.  Execute it on your machine, it will blow up.  And you can see for yourself.

**Comment by NickCraver** [comment] 2020-05-02 19:21
First, I am trying to help you. I was asking what the error message was _from the second piece of code_ - I cannot assume it's the exact same. That's why I asked.

Let's be clear: those are _very_ different examples. The first is trying to put multiple parameters into a single string inside of a SQL statement, which isn't at all supported (in SQL Server itself). The second looks completely reasonable, but what it's doing very much depends on the model since that's what the parameter parsing is based on. The input from your model, if that throws the same error, very much matters.

I _have_ grabbed your original example - but as I said: I have no expectation that it would or should work. That's just not valid SQL as far as I'm aware. The fact that the invalid SQL breaks a regex match in Dapper doesn't concern me because _it's not valid_, and there's no way to "fix" it, because it'd just not do anything expected if we made...something...work.

If you're willing to provide the model in the second example, I'll still take a look despite your tone in replies. If you'll look back, I've been trying to ascertain your issue with more information the entire time. I'll remind you that this is a free library and we are under no obligation to help. We do this in our free time only.

**Comment by briankitt** [comment] 2020-05-02 19:38
What, do you want my entire app and database?

**Comment by briankitt** [comment] 2020-05-02 19:39
Closing this because I simply cannot get my point across and I have better things to do than play merry go round

**Comment by NickCraver** [comment] 2020-05-02 19:43
> What, do you want my entire app and database?

No, [I very narrowly scoped the ask to](https://github.com/StackExchange/Dapper/issues/1442#issuecomment-622995215):

> What is `modelFormData` here?

If you open an issue in this organization again, please be do not be a jerk to whomever is trying to help you. It will not be tolerated and will result in being blocked from the organization.

**Comment by briankitt** [comment] 2020-05-02 19:49
I am no the one being the jerk?  I'm trying to be as simple as possible, and you just keep trying to run around in circles.  You are making me angry because you just keep running around in totally different directions?  

I have a very complex application, and rather than give you 2000 lines of code to debug, I tried to narrow the problem down to about 6 lines of code so you can

**Comment by briankitt** [comment] 2020-05-02 20:00
I am not the one being a jerk, what have I done that makes me a jerk?  I simply am trying to figure out why my generated SQL causes such a bizarre error?
You are just running me around in circles to the point where I find this whole conversation pointless.

I didn't want to give you 2000 lines of code to debug, because I thought that would be pointless.  So rather than give you 2000 lines of code to debug, I tried to come up with a very simple example of some SQL that would give the same error I was getting.

Of course I get that the original SQL doesn't do anything constructive.  It's simple an example of how to recreate the error.  That is NOT the SQL I am executing, but it's an example that illustrates the error, in a way that anyone can execute it and test it.
Of course I get that my second example was VERY different.  I was trying to illustrate a point that if I gave you a more specific example, then you were going to need a lot of extra information that wasn't pertinent (such as modelformdata and the schema for tblContactForm).
Of course I know that you don't know what modelformdata is.  I was trying to illustrate a point that I intentionally made the original example as simple as possible so that it did not require you to need any of my application specifics.

My whole point, was I was trying to give you a way to recreate the error, without requiring you to do 10 minutes of setup work.   

Then you go off on a tangent saying my example doesn't do anything.  Of course I know that.  I was trying to make YOUR job easier, by just making an example that you could execute in 30 seconds and say 'this is why it fails'.

Don't be calling other people a jerk, when you are just missing the point.  I tried to make this problem very simple for you to recreate, and then you go off on a tangent saying my problem is not valid because the SQL doesn't do anything.

I simply tried to put the error in as small of an example as I could so you could easily figure this out.

I tried to do you a favor.  'No good deed goes unpunished' is rining very true right now.

**Comment by NickCraver** [comment] 2020-05-02 20:06
I only asked you for the model passed in, in an attempt to help. I also did so politely, several times, despite your tone. You've taken far more time to berate those trying to help you than answering the questions they're asking...to help you.

Since you're not interested in actually getting help - I'm closing this issue and removing your access to this organization.

**Closed by NickCraver** 2020-05-02 20:06 UTC
Labels: needs-info

**Comment by mgravell** [comment] 2020-05-02 20:40
Independent eyes walking in.

To explain the problem: for us, as maintainers, to investigate and try to resolve this, the first thing we need is a minimal reproducible example that causes the same problem you are trying to describe. Now, we can take a *stab* at that, but - if we need to guess too much, there is no guarantee that we're investigating the same problem, *especially* when the original example doesn't make sense in the first place. And investigating a different scenario isn't useful to you or us.

That's why the best place to start is a minimal *runnable* repro. That doesn't mean your entire codebase. Our test suite has many, many examples of minimal repros that configure a dummy throwaway schema (with or without data) in a few lines of code, then shows the problem. Without needing your app code.

There's a secondary advantage to putting together a minimal repro: a high percentage of times, when you try to put together a minimal repro, you find it actually works fine, and the problem isn't where you think it is. That means you can often solve the problem simply by looking at what is different between the sample and the real code, so frankly it is an **invaluable** tool / skill in itself.
