### ISSUE TITLE
problem to install dapper package

### ISSUE THREAD

**Issue by gpcongom** [StackExchange/Dapper#975] opened 2018-03-19 19:44 UTC
I am trying to install dapper and it throws me the following error.

PM> Install-Package Dapper
Install-Package : 'Dapper' ya tiene una dependencia definida para 'System.Data.SqlClient'.
At line:1 char:1
+ Install-Package Dapper
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by mgravell** [comment] 2018-03-19 19:49
What platform are you targeting?

**Comment by gpcongom** [comment] 2018-03-19 19:57
Windows server 2016 standard 64x

**Comment by mgravell** [comment] 2018-03-19 20:04
I meant what *framework/tfm* are you targeting? Sorry, that's my bad - I
shouldhave been clearer. For example, ".NET Framework 4.5", ".NET Framework
4.71" or ".NET Standard 2.0", etc

On 19 Mar 2018 7:57 pm, "gpcongom" <notifications@github.com> wrote:

Windows server 2016 standard 64x

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/975#issuecomment-374350126>,
or mute the thread

**Comment by gpcongom** [comment] 2018-03-19 20:06
VS 2012 (.NET Framework 4.5)

**Comment by mgravell** [comment] 2018-03-19 20:06
Also, translating that error, it seems to.be a duplicate reference. Can I
ask what other references you have? I wonder if somehow so.ethig is
targeting another different SqlClient?

**Comment by gpcongom** [comment] 2018-03-19 20:15
I deleted all references and only the reference to system remained.
It is a class library project that is empty.

**Comment by mgravell** [comment] 2018-03-19 20:26
Hmmm; the top version on nuget (1.50.4) only supports a minimum of .NET 4.5.1

If you are really on 4.5, then maybe:

    Install-Package Dapper -Version 1.50.2

however, I'm unable to reproduce your exact error message; here's a .NET 4.5 class library project installing 1.50.2:

PM> Install-Package Dapper -Version 1.50.2

```
Attempting to gather dependency information for package 'Dapper.1.50.2' with respect to project 'ClassLibrary8', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 1.16 sec
Attempting to resolve dependencies for package 'Dapper.1.50.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Dapper.1.50.2'
Resolved actions to install package 'Dapper.1.50.2'
Retrieving package 'Dapper 1.50.2' from 'nuget.org'.
Adding package 'Dapper.1.50.2' to folder 'C:\Users\marcg\OneDrive\Documents\Visual Studio 2017\Projects\ClassLibrary8\packages'
Added package 'Dapper.1.50.2' to folder 'C:\Users\marcg\OneDrive\Documents\Visual Studio 2017\Projects\ClassLibrary8\packages'
Added package 'Dapper.1.50.2' to 'packages.config'
Successfully installed 'Dapper 1.50.2' to ClassLibrary8
Executing nuget actions took 793.94 ms
Time Elapsed: 00:00:02.0197167
```

It could be that this is a VS2012 issue. It is increasingly difficult for us to support old IDEs - we typically use VS2017. Is there a specific reason you are using VS2012?

**Comment by gpcongom** [comment] 2018-03-19 20:27
And now I was able to install version 1.5.2 of dapper, but I could not install version 1.5.4.
-----Dapper 1.50.2
Install-Package Dapper -Version 1.50.2
Instalando 'Dapper 1.50.2'.
'Dapper 1.50.2' se instaló correctamente.
Agregando 'Dapper 1.50.2' a ................................................................
'Dapper 1.50.2' se agregó correctamente a .................................................................


-----Dapper 1.50.4
Install-Package : 'Dapper' ya tiene una dependencia definida para 'System.Data.SqlClient'.
At line:1 char:1
 Install-Package Dapper -Version 1.50.4
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
 FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand


Can I use dapper for Oracle?

**Comment by mgravell** [comment] 2018-03-19 20:32
Dapper is *largely* provider agnostic - and yes it can be used with Oracle. I don't know why you're seeing that error  - I can only guess it is your older nuget client tools getting upset :(

**Comment by gpcongom** [comment] 2018-03-19 20:35
Yes, it's strange, I always use dapper in my projects and it's the first time it happens to me. Delete and create the same class library but I could never install version 1.50.4

Thank you very much for your help.

**Comment by mgravell** [comment] 2018-03-19 20:38
1.50.4 is the first version that drops .NET 4.5, moving to .NET 4.5.1. In our defence: "extended support" for both 4.5 and 4.5.1 ran out in January 2016

**Comment by gpcongom** [comment] 2018-03-19 20:55
I am using VS 2012 due to customer requirements. But with Dapper 1.50.2 it is enough for this project, thank you very much.

**Comment by NickCraver** [comment] 2018-03-30 00:55
Closing out to cleanup :)

**Closed by NickCraver** 2018-03-30 00:55 UTC

**Comment by Rekhachandrashekar** [comment] 2018-05-24 04:10
when I tried to install Dapper from nuget packages I am getting the below error 
And also I am using .net framwork version 4.5 
please help me to come out of this error

Could not install package 'Dapper 1.50.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mgravell** [comment] 2018-05-24 19:10
The last version with 4.5 support was 1.50.2; the current version supports
4.5.1 and above. I cannot remember why, but there was presumably a reason.
So: either target library 1.50.2, or framework 4.5.1 (or above).

**Comment by smashraid** [comment] 2018-08-17 16:54
Hi I need help I try to add the nuget in a Client Library project Framework 4.5 Visual Studio 2017 but I'm getting an error

Could not install package 'Dapper 1.50.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

![image](https://user-images.githubusercontent.com/2209373/44278669-54c45a00-a214-11e8-8566-ecdd1fdfc670.png)

**Comment by oghenez** [comment] 2021-01-12 07:43
From [Stackoverflow](https://stackoverflow.com/questions/45103492/an-error-occurred-while-retrieving-package-metadata-for/45225236)

Update the Visual Studio Package Manager to the latest version using the below steps and the ongoing issue will disappear.

In Visual Studio, from the "Tools" menu choose the "Extensions and Updates" option.
From the dialog that appears, expand the "Updates" node from the tree at the left side.
Select the "Visual Studio Gallery" option from the tree.
Finally, look for the Package Manager update in the list of updates at the right side of the dialog and click the "Update" button beside it.
