### ISSUE TITLE
ExecureReaderAsync returning closed IDataReader

### ISSUE THREAD

**Issue by xmaiconx** [StackExchange/Dapper#758] opened 2017-04-27 19:22 UTC
Hi!

I'm trying to use ExecuteReaderAsync, but it is throwing an exception 'Invalid attempt of read when the reader is closed.'. 
After googling, I found some answers that the connection is closed before read the result, but I checked my code and the connection still opened.
When I use the method ExecuteReader (not async), it works.

Preview of my code:

```c#
var cmd = new CommandDefinition(search.Query, params, Session.Transaction, commandType: System.Data.CommandType.Text);
var r = await Session.Connection.ExecuteReaderAsync(cmd).ConfigureAwait(false);

using (r)
{
	while (r.Read())
	{
		var data = new SomeObject();

		foreach (var item in search.Fields)
		{
			switch (item.Field)
			{
				case "id":
					data.Id = Convert.ToDouble(r["id"]);
					break;

				case "name":
					data.Name = Convert.ToString(r["name"]);
					break;

				default:
					break;
			}
		}

		results.Add(data);
	}
}
```

If I change to this:
```c#
var cmd = new CommandDefinition(search.Query, params, Session.Transaction, commandType: System.Data.CommandType.Text);
var r = await Task.FromResult(Session.Connection.ExecuteReader(cmd)).ConfigureAwait(false);
```
It works.

Could you check it, please?

Thank you.

**Comment by xmaiconx** [comment] 2017-11-14 14:04
Hi guys!

I saw that this issue was referenced in #656 and you have doubts about executing many queries in a single connection. Just to show that my connection is always scoped and in this case it executes just one time.
In this code below I needed to wrap the ExecuteReader into a Task.FromResult again to get it work:

```c#
public Task<IDataReader> ExecuteReport(string sp, IEnumerable<Parametro> parametros)
{
	var conn = ConnectionProvider.Connection;
	var dynamicParams = new DynamicParameters();

	if (parametros != null)
	{
		foreach (var item in parametros)
		{
			if (item.Tipo == TipoParametroValor.Texto)
				dynamicParams.Add(item.Nome, item.Valor, DbType.String, size: item.Max > 0 ? (int?)item.Max : null);
			else
				dynamicParams.Add(item.Nome, item.Valor, Converters.GetDbType(item));
		}
	}

	return Task.FromResult(conn.ExecuteReader(
		sql: sp,
		commandType: CommandType.StoredProcedure,
		param: dynamicParams,
		transaction: ConnectionProvider.CurrentTransaction));
		
	//return conn.ExecuteReaderAsync(
		//    sql: sp,
		//    commandType: CommandType.StoredProcedure,
		//    param: dynamicParams,
		//    transaction: ConnectionProvider.CurrentTransaction);
}

using (var conn = new VendasConnectionProvider(new VendasStringConnectionProvider(mapeamento)))
{
	conn.Connection.Open();
	var repository = new RelatorioDataRepostory(conn);
	var dr = await repository.ExecuteReport(relatorio.Procedure, ParametersConverter.MapearParametros(settings.ParametrosRelatorio, relatorio.Parametros));
	
	while (dr.Read())
	{
		Debug.WriteLine($"Nome: {dr["nome"]}");
	}
}
```

Hope that helps.

**Comment by bgrainger** [comment] 2018-08-21 21:42
Assuming this started happening with MySql.Data 6.10.x (and didn't happen with 6.9.x), I think you're running into the problem I described here: https://github.com/StackExchange/Dapper/issues/1101#issuecomment-414830916

**Comment by NickCraver** [comment] 2018-09-09 22:41
As @bgrainger says (thanks!) this seems to be a dupe. If it's *not* a dupe of #1101, please poke and we'll reopen :)

**Closed by NickCraver** 2018-09-09 22:41 UTC
