### ISSUE TITLE
connection is already in state 'Executing' when inserting lots of objects

### ISSUE THREAD

**Issue by thedumbtechguy** [StackExchange/Dapper#919] opened 2018-01-12 16:52 UTC
I am trying to insert about 11k (11244 to be precise) rows using ExecuteAsync.
I am using Dapper with Npgsql.

I was testing incrementally but as soon as I tried 11k rows I got the exception below.

```
Npgsql.NpgsqlOperationInProgressException: The connection is already in state 'Executing'
   at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<>c__DisplayClass83_0.<<ExecuteNonQueryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteMultiImplAsync>d__36.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 622
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

I traced it down to https://github.com/StackExchange/Dapper/blob/a213b2aeee66ac0bff327ff19e70516fb629abe3/Dapper/SqlMapper.Async.cs#L622

The error is common when calls to the database are not awaited.
The line, however, seems to be awaited.

Any help will be appreciated

**Comment by thedumbtechguy** [comment] 2018-01-12 19:05
Some more information.

The error happens on when I make multiple calls to `ExecuteAsync`.

I am at a total loss now what is going on.

**Comment by thedumbtechguy** [comment] 2018-01-13 15:22
I've opened a ticket on npgsql repo as well

https://github.com/npgsql/npgsql/issues/1776

**Comment by mgravell** [comment] 2018-01-13 15:39
I can try to check later, but AFAIK we correctly `await` each operation here unless you're using the opt-in pipeline / MARS mode, which you haven't done. Very interesting!

**Comment by thedumbtechguy** [comment] 2018-01-13 15:41
I checked and you do await all calls.
I am hoping the @roji would be able to help.

**Comment by thedumbtechguy** [comment] 2018-01-20 17:29
For anyone wondering, I switched to using [postgresql_bulk_insert](https://bytefish.de/blog/postgresql_bulk_insert/) for the larger inserts.
It works very very fast.

**Comment by rexlam0630** [comment] 2018-07-11 05:13
I had the same problem, when calling multiple time to `ExecuteAsync` method with `awaited` in single transaction scope (and the same connection as well).

Dapper version: 1.50.4
Npgsql version: 4.0.0

Stack trace:
```
Npgsql.NpgsqlOperationInProgressException: A command is already in progress: INSERT INTO "answer"("create_date","request_id","question_id","answer","display_order") VALUES (@P0,@P1,@P2,@P3,@P4);
   at Npgsql.NpgsqlConnector.<StartUserAction>g__DoStartUserAction|186_0(<>c__DisplayClass186_0& ) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1648
   at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1661
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1044
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__37.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 646
```

Traced down to:
https://github.com/StackExchange/Dapper/blob/4b746010ea81f758adc2d0cadaecb157f0a638bf/Dapper/SqlMapper.Async.cs#L646

**Comment by roji** [comment] 2018-07-11 05:41
Guys, I'm very interested in finding and fixing this issue, but up to now nobody has provided a simple code sample that reproduce the issue - a simple console program would do.

If the error isn't deterministic, it's usually possible to loop for a large number of iterations until the error occurs.

Without a code sample it simply isn't possible to investigate this.

**Comment by rexlam0630** [comment] 2018-07-11 09:32
Sorry about that, I just found this issue a few hours ago, and still haven't had time to prepare the reproduce steps or a console application.

I just provide a quick update here,

I can't post the whole program here, but it is just like:
```
using (conn)
  using (transaction)
  {
    foreach (var toInsert in toInserts) {
      await conn.ExecuteAsync(toInsert.sql, toInsert.parameters, transaction, commandTimeout);
    }
  }
}
```

and it will throw an exception while the loop comes to 2nd round.

I changed the code to below to make use of Dapper bulk execute function:
```
using (conn)
  using (transaction)
  {
    var sql = string.Empty;
    var parametersList = toInserts.Select(x =>
    {
      sql = x.sql;
      return x.parameters;
    });
    
    await conn.ExecuteAsync(sql, parametersList, transaction, commandTimeout);
  }
}
```

everything seems fine.

**Comment by roji** [comment] 2018-07-11 09:48
@rexlam0630 thanks for responding. From your description it seems like it should be relatively easy to reproduce reliably, I hope you can make an effort on this and submit a full code sample (database schema + C# console program). Once I can see the issue happening here it should be relatively easy to find the cause and fix it.

**Comment by roji** [comment] 2018-07-12 07:32
@rexlam0630 yes, you're trying to concurrently use the same connection, which you cannot do. Note that you can pack several INSERT statements into the same command's CommandText, separated by semicolons, rather than executing in different command. This makes Npgsql send them in a single network round-trip, making the whole operation much faster.

**Comment by rexlam0630** [comment] 2018-07-12 08:04
@roji Um... I'm getting more confused now...

Did the following codes make any different in term of connection?
Why things only happen on the 2nd pattern, not both? what is under the hood...
```
await conn.ExecuteAsync(sql1, param1, transaction);
await conn.ExecuteAsync(sql2, param2, transaction);
await conn.ExecuteAsync(sql3, param3, transaction);
await conn.ExecuteAsync(sql4, param4, transaction);
```
```
var tasks = new List<Task>
{
    conn.ExecuteAsync(sql1, param1, transaction),
    conn.ExecuteAsync(sql2, param2, transaction),
    conn.ExecuteAsync(sql3, param3, transaction),
    conn.ExecuteAsync(sql4, param3, transaction)
};

await Task.WhenAll(tasks); 
```

Besides, what is the best practice/your suggestion of inserting multiple items in a single transaction without packing all statements into same `CommandText`? or packing it all is the only way out?
Thanks again!

**Comment by rexlam0630** [comment] 2018-07-12 09:02
@vdaron Why did the `foreach` loop with `await` make no difference with `WhenAll`? 

From my understanding, the `WhenAll` execute the tasks at the same time (parallel) but the `foreach` loop with `await` is actually waiting for the current task complete before starting the next iteration? Am I wrong?

**Comment by roji** [comment] 2018-07-12 09:40
@rexlam0630 you need to understand a bit more about how async/await really works. When you call `ExecuteAsync()`, the method starts executing immediately and synchronously. When it hits the first yielding await (i.e. I/O) operation, the method will stop executing and set up a callback to run when the operation completes.

When you write the following code:

```c#
var tasks = new List<Task> {
    conn.ExecuteAsync(sql1, param1, transaction),
    conn.ExecuteAsync(sql2, param2, transaction),
    conn.ExecuteAsync(sql3, param3, transaction),
    conn.ExecuteAsync(sql4, param3, transaction)
};
```

The first `ExecuteAsync()` starts executing, and then yields when it first does any I/O. Since you did not await it, our thread continues to the second `ExecuteAsync()`, which fails immediately because the first one is still in progress.

Finally, regarding inserting multiple items... I don't know Dapper very well, but at the SQL level you can simply do `INSERT INTO table (x, y) VALUES (1,2), (3,4)` and you've inserted two rows in a single statement (and single network roundtrip). You can also pack multiple statements into a single command by setting CommandText to `INSERT INTO table (x, y) VALUES (1,2); INSERT INTO table (x, y) VALUES (3,4)`, which will again work in a single network roundtrip. If you're inserting many rows, the second option can be better since it can benefit from preparation (but read [the Npgsql docs](http://www.npgsql.org/doc/prepare.html) to understand that better). Finally, if you're really inserting lots of rows and are interested in maximum perf, look at [Npgsql's bulk copy support](http://www.npgsql.org/doc/copy.html), which is the fastest possible method (but works totally outside Dapper).

All of the above has nothing to do with *transactions*, but rather about inserting multiple rows in a single network roundtrip (which may or may not correspond to a transaction).

**Comment by rexlam0630** [comment] 2018-07-12 10:37
You’re right, it totally makes sense, thanks all again!

**Comment by NickCraver** [comment] 2020-05-02 18:07
Thanks a lot @roji - closing this out to cleanup :)

**Closed by NickCraver** 2020-05-02 18:07 UTC
