### ISSUE TITLE
Implicit then explicit cast causes error

### ISSUE THREAD

**Issue by JAschmann** [StackExchange/Dapper#277] opened 2015-04-24 07:22 UTC
I am using Dapper 1.39 for .NET 4.5.2 and using QueryAsync from a stored procedure into a .NET object.

 If the return result from the procedure has columns that are not type specified and the cast is implicit to the .NET object through Dapper then everything works perfectly. If the result from SQL has the types specified everything works perfectly. The issue occurs when you are making calls to the procedure and the type is not specified and Dapper is doing an implicit cast, and then you change the procedure or it takes a different code path and returns the same result which is typed. The change can occur on a single column.

Dapper will throw the following error, on any subsequent calls regardless if the type is specified or not:

``` JSON
"ClassName": "System.Data.DataException",
"Message": "Error parsing column 10 (x=1000.00 - Decimal)",
"Data": null,
"InnerException": 
 {
    "ClassName": "System.InvalidCastException",
    "Message": "Specified cast is not valid.",
```

An IIS reset will fix the issue until the scenario is repeated so the caching of the type is the problem in that Dapper implicit type is different to the actual type.

**Comment by mgravell** [comment] 2015-04-24 08:50
In the above example:  what was the change? Basically, I'd like to try and get a solid repro together (perhaps using `CREATE PROC`, `Query<Foo>`, `ALTER PROC`, `Query<Foo>`).

**Comment by ebellas** [comment] 2015-05-28 03:38
Not meaning to hijack this issue, but this sounds very similary to #264, but I have not been able to reproduce

**Comment by JAschmann** [comment] 2015-06-18 15:48
Here is the step by step reproduction of the issue. I am using Dapper 1.40 and MSSQL 2008.

1) I wrote a simple console application. It will loop and call the same procedure twice using Dapper:
![1 2](https://cloud.githubusercontent.com/assets/12095394/8234884/118f52cc-15df-11e5-8ae6-3a4c43a8bf18.PNG)

2) The procedure will return the value 1, the first time SQL it is not typed and the second time it is converted to decimal:
![2](https://cloud.githubusercontent.com/assets/12095394/8234978/8de2fc8e-15df-11e5-9137-37cf7d5a7d93.PNG)

3) The value will be returned into an object as a non nullable decimal:
![3](https://cloud.githubusercontent.com/assets/12095394/8235001/bec4677a-15df-11e5-8441-f31722fe49f1.PNG)

4) As expected on the first iteration with the implicit conversion the value of TestValue is 1: 
![4](https://cloud.githubusercontent.com/assets/12095394/8235107/53deb072-15e0-11e5-85fe-d1c0491b994a.PNG)

5) However on the second iteration when the conversion to decimal is explicit an error is thrown:
![5](https://cloud.githubusercontent.com/assets/12095394/8235220/0ae839f0-15e1-11e5-8e04-4699908a4cc5.PNG)

The error is that the specific cast is not valid, however "1.00" is a legitimate decimal value.

6) If I reverse the order, and cast to decimal first then on the second iteration I get this error that it is now trying to cast as int:
![6](https://cloud.githubusercontent.com/assets/12095394/8235342/b5edf7b8-15e1-11e5-9b08-d7e75b2a8407.PNG)

So there must be caching on the column when the type is changed or specified then a conversion error occurs.

**Comment by NickCraver** [comment] 2015-10-24 15:26
Correct, you're hitting the deserializer cache here - part of what makes Dapper vast fast. We may need to look at cache invalidation in cases such as this, but there is a danger there of re-generating the serializer on *every* error (for example when you pass a bad mapping). But if the alternative is *throwing an exception*, maybe that's not such a bad fallback universally. Thoughts @mgravell? We love adding `goto` statements and this seems like an excellent opportunity...

**Comment by nquoctuan** [comment] 2016-03-03 09:35
Any solution to fix the issue, it repeatedly happens on my system, even try to clear cache of dapper - 
`SqlMapper.PurgeQueryCache()` , 

but still happens. Anyone give me an advice?

**Comment by mgravell** [comment] 2016-03-03 10:42
@nquoctuan a lot has changed since this bug was originally logged; and the cache-breaker was changed to include type changes in c80e9d17488425006de1b6e33dc3989ab7251e84 - which manifests in builds from 1.50-beta7 onwards. Don't stress about the "beta" in that name - that is just because the package includes ".net core" builds, which is not RTM - but if you aren't targeting ".net core" that won't affect you. Can you see whether the issue still happens with 1.50-beta7 or 1.50-beta8 ?

**Comment by nquoctuan** [comment] 2016-03-03 11:57
@mgravell Currently I use dapper version 1.42. As you mentioned, 1.50-beta7 does not affect on Windows Server ? If yes, then I am very happy to deploy on production.

Thanks mgravell

**Comment by mgravell** [comment] 2016-03-03 12:19
We're using 1.50.0-beta8 in production on regular .NET and have been since it was pushed to nuget; the "beta" in there relates only to the fact that it contains DNX bits. For some other packages, I have pushed a separate slimmed down package (minus the DNX bits and minus the suffix), but... whatever ;) Basically, yes, it should be fine in production (to the best of my knowledge etc).

**Comment by tompazourek** [comment] 2016-04-06 15:04
I had the same problem and I found out why it happened in my case.

My SQL query was a stored procedure with something like this inside:

```sql
IF EXISTS (...)

	SELECT x.[Price], ...

ELSE

	SELECT 0
```

The `Price` column had type `money` and it was complaining that it cannot parse it as decimal.

I think the problem is that when the query was in the `ELSE` branch, it returned 0 with the `int` type, so Dapper expected that the next value will be `int` as well, but got `money` instead.

I fixed it using this change:

```sql
IF EXISTS (...)

	SELECT x.[Price], ...

ELSE

	SELECT CAST(0 AS money)
```

**Comment by mgravell** [comment] 2016-04-06 22:54
What version number are you using? The latest builds (technically marked
beta, because: damn you core-clr) include changes to including more type
metadata in the hash when comparing table structures, which should fix
this. If you're using anything before 1.50-beta7, I would expect this to
fail in the way you describe. If you're using anything >= this, it sounds
like it needs more love. So: what version number are you using?

Also: by the time you've checked for existence, you might as well have just
selected the record. Personally, I'd rather use something like
QueryFirstOrDefault
/ QuerySingleOrDefault and check for null - that way, no double-hit (these
methods are also new in 1.50.something).

On 6 April 2016 at 16:04, Tomáš Pažourek <notifications@github.com> wrote:

> I had the same problem and I found out why it happened in my case.
>
> My SQL query was a stored procedure with something like this inside:
>
> IF EXISTS (...)
>
>     SELECT x.[Price], ...
>
> ELSE
>
>     SELECT 0
>
> The Price column had type money and it was complaining that it cannot
> parse it as decimal.
>
> I think the problem is that when the query was in the ELSE branch, it
> returned 0 with the int type, so Dapper expected that the next value will
> be int as well, but got money instead.
>
> I fixed it using this change:
>
> IF EXISTS (...)
>
>     SELECT x.[Price], ...
>
> ELSE
>
>     SELECT CAST(0 AS money)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/277#issuecomment-206417774>
>



-- 
Regards,

Marc

**Comment by tompazourek** [comment] 2016-04-07 08:15
@mgravell: I was using 1.42, so it is as you expected.

btw. You're absolutely right about the better `QueryFirstOrDefault` approach, I had some internal reasons that persuaded me to implement it this way (mainly reusability and compatibility concerns with other code).

Anyway, I think that the SP should probably return columns of the same types regardless of the control flow inside, so I am good with the fix I used even though it might not be needed in the newer version of Dapper.

**Comment by NickCraver** [comment] 2018-05-20 12:10
Fix in latest, so closing this out :)

**Closed by NickCraver** 2018-05-20 12:10 UTC
Labels: needs-investigation
